name: accounting_app
description: A personal accounting app for Android.
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  crypto: ^3.0.3
  intl: ^0.18.1
  fl_chart: ^0.65.0
  cupertino_icons: ^1.0.6
  share_plus: ^7.2.1
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true